name: Release Obsidian plugin

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "14.17.3"

            - name: Build plugin
              run: |
                  npm install
                  npm run build:esbuild
                  npm run build:css

            - name: Move manifest file
              run: |
                  cp ./manifest.json ./public/manifest.json
                  
            - name: Archive Release
              uses: thedoctor0/zip-release@0.7.5
              with:
                type: 'zip'
                filename: 'obsidian-simple-pta.zip'
                directory: ./public

            - name: Generate release
            - uses: ncipollo/release-action@v1
              with:
                artifacts: "obsidian-simple-pta.zip"
